#!/usr/bin/python3
from html.parser import *
from urllib.request import *
from subprocess import *
lowestLoadServer = "none"
class MyHTMLParser(HTMLParser):
    encounteredContent = 0
    lowestLoad = 100
    global lowestLoadServer
    def handle_starttag(self,tag,attrs):
        if(tag == "div"):
            if(attrs[0][1] == "content"):
                self.encounteredContent = 4
    def handle_comment(self, data):
        global lowestLoadServer
        if(self.encounteredContent):
            self.encounteredContent = self.encounteredContent - 1
            if(self.encounteredContent == 0):
                servers = data.split("\\n")
                for i in servers:
                    parts = i.split(',')
                    if(len(parts) > 6):
                        load = float(parts[4].split()[2]) - float(parts[2])
                        server = parts[0].lstrip("\'b\'")
                        server = parts[0].lstrip("\"b\'")
                        if(self.lowestLoad > load and not server.startswith("linuxremote")):
                            self.lowestLoad = load
                            lowestLoadServer = server

f = urlopen("http://it.engineering.iastate.edu/remote")

feed = ""
for line in f:
    try:
        data = str(line)
    except EOFError:
        break
    feed = feed + data

parser = MyHTMLParser()
parser.feed(feed)
login = "ktown@" + lowestLoadServer
call(["ssh", "-X", login])
